CFLAGS  = -Wall -Wno-format-truncation -fPIC -ggdb -O2 -m32 $(OPTS) $(INCLUDE) $(DEFINES) -fdata-sections -ffunction-sections 
LDFLAGS = -m32 -s -lpthread -ldl -lm -lrt -L. 
# -l:libssl.a -l:libcrypto.a to force link with static version
# for LD debug -s

HOST = linux
PLATFORM = x86

include Makefile

