CC = arm-linux-gnueabi-gcc
CFLAGS  = -Wall -Wno-format-truncation -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS = -s -lpthread -ldl -lm -lrt -L. 
# for LD debug -s

HOST = linux
PLATFORM = armhf

include Makefile

