CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES) -fdata-sections -ffunction-sections 
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -lz -L. 
#LDFLAGS ?= -s -lpthread -l:libssl.a -l:libcrypto.a -ldl -lm -lrt -lz -L. 
# for LD debug -s

OBJ					= bin/x86
EXECUTABLE 			= ../bin/airupnp-x86
#EXECUTABLE_STATIC	= ../bin/airupnp-x86-static

include Makefile

