CC	 	= armv5te-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -L. 

# for LD debug -s

OBJ					= bin/arm5
EXECUTABLE 			= ../bin/airupnp-arm5
#EXECUTABLE_STATIC	= ../bin/airupnp-arm5-static

include Makefile

