CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. 

# for LD debug -s

OBJ					= bin/aarch64
EXECUTABLE 			= ../bin/airupnp-aarch64

include Makefile

