CC=powerpc-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lpthread -lssl -lcrypto -ldl -lm -lrt -L. 

OBJ					= bin/ppc
EXECUTABLE 			= ../bin/airupnp-ppc

include Makefile

