CC=powerpc-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. 

OBJ					= bin/ppc
EXECUTABLE 			= ../bin/airupnp-ppc
#EXECUTABLE_STATIC	= ../bin/airupnp-ppc-static

include Makefile

