CC	 	= armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lpthread -lssl -lcrypto -ldl -lm -lrt -L. 
# for LD debug -s

OBJ					= bin/arm
EXECUTABLE 			= ../bin/airupnp-arm

include Makefile

