/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "castmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CastMessage, CastMessage, 2)


PB_BIND(AuthChallenge, AuthChallenge, AUTO)


PB_BIND(AuthResponse, AuthResponse, AUTO)


PB_BIND(AuthError, AuthError, AUTO)


PB_BIND(DeviceAuthMessage, DeviceAuthMessage, AUTO)






