#CC	 	= armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -L. 
# for LD debug -s

OBJ					= bin/arm64
EXECUTABLE 			= ../bin/aircast-arm64

include Makefile

