CC=powerpc-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -L. 

OBJ				= bin/ppc
EXECUTABLE 			= ../bin/aircast-ppc
EXECUTABLE_STATIC 		= ../bin/aircast-ppc-static

include Makefile

