CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -arch x86_64
LDFLAGS ?= -lpthread -lssl -lcrypto -ldl -lm -L. -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -arch x86_64 -mmacosx-version-min=10.5

OBJ					= bin/osx
EXECUTABLE 			= ../bin/aircast-osx-multi

include Makefile

