CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -L. 
# for LD debug -s

OBJ					= bin/aarch64
EXECUTABLE 			= ../bin/aircast-aarch64

include Makefile

