CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES) -fdata-sections -ffunction-sections 
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -lz -L. 
# for LD debug -s

OBJ					= bin/x86
EXECUTABLE 			= ../bin/aircast-x86

include Makefile

