CC=x86_64-cross-freebsd11-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES) -fdata-sections -ffunction-sections 
LDFLAGS ?= -s -lpthread -lm -lrt -lz -L. 
# for LD debug -s

OBJ					= bin/bsd-x64
EXECUTABLE 			= ../bin/aircast-bsd-x64
EXECUTABLE_STATIC 			= ../bin/aircast-bsd-x64-static

include Makefile

