CFLAGS  ?= -Wall -fPIC -ggdb -O2 -m64 $(OPTS) -I/usr/include/i386-linux-gnu $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -m64 -lpthread -ldl -lm -lrt -L. 

HOST = linux
PLATFORM = x84

OBJ					= bin/$(PLATFORM)
EXECUTABLE 			= ../bin/aircast-$(PLATFORM)

include Makefile

