CC = i686-linux-gnu-gcc
CFLAGS  = -Wall -Wno-format-truncation -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES) -fdata-sections -ffunction-sections 
LDFLAGS = -s -lpthread -ldl -lm -lrt -L. 
# for LD debug -s

HOST = linux
PLATFORM = x86

include Makefile


