CC=sparc-cross-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -L. 

OBJ					= bin/sparc
EXECUTABLE 			= ../bin/aircast-sparc

include Makefile

